### ISSUE TITLE
这个参数是什么含义啊？“SIFT_FIXPT_SCALE”

### ISSUE THREAD

**Issue by lxlscut** [o0o0o0o0o0o0o/image-processing-from-scratch#3]

**Comment by mam-mon** [comment]
请问您是？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lxlscut"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月15日(星期天) 下午4:37
收件人:&nbsp;"o0o0o0o0o0o0o/image-processing-from-scratch"<image-processing-from-scratch@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[o0o0o0o0o0o0o/image-processing-from-scratch] 这个参数是什么含义啊？“SIFT_FIXPT_SCALE” (#3)
