### ISSUE TITLE
Image size not reduced with PCA

### ISSUE THREAD

**Issue by Neelam96** [o0o0o0o0o0o0o/image-processing-from-scratch#6]
I tried using your codes for PCA&SVD and tested it on 0.jpg (21.9 kB) image provided, I found out that in spite of using PCA, the size of image 0_.jpg (73.1 kB) is not reduced.
Any leads will be helpful

**Comment by o0o0o0o0o0o0o** [comment]
That's because 0_.jpg is actually already reconstructed, the program compress 0.jpg first using PCA, and then reconstruct the image using compressed data(some eigenvectors and the projection of the original image), so that we can see the result and compare the difference with the original image.

**Comment by Neelam96** [comment]
Thanks for the explanation, now I get it :)
